name: Run tests

on:
  workflow_dispatch: 
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set up node 20 
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-dependencies: true
      - run: |
          cd backend
          mvn clean spring-boot:run & 
          echo "waiting 5 seconds for the server to start"
          sleep 10
          attempt_counter=0
          max_attempts=5
          echo "sever ready for testing"
          cd ..
          cd frontend
          cd src
          python3 -m http.server 8000 &
          sleep 10 &&
          curl http://localhost:8000
          cd ..
          cd tests
          npm install
          ./node_modules/.bin/mocha *.js

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/
